### ISSUE TITLE
Potentially incorrect initial attention

### ISSUE THREAD

**Issue by kawu** [ShenMinX/point-gen#6]
Initially you have:
```python
attn = torch.ones(batch_size, max_sl).to(device) # init_attn
```
This does not seem to respect the definition of an attention (which should sum up to one for each sentence in the batch).  Isn't it used for the calculation of the coverage in the first step of the decoding process?  If so, it may have a negative impact on the operation of the coverage mechanism.

**Comment by kawu** [comment]
I think I was wrong, the initial attention is not used for the calculation of the coverage in the first decoding step.  However, it's used to calculate the `context`, right?  So if the initialization is incorrect, it can still have some impact on the decoding process (although maybe not on the coverage part).

**Comment by ShenMinX** [comment]
@kawu Fixed, attention is now calculated first in decoder, and there is no need to pass it between iteration, and therefore no need for attn_0.

**Comment by kawu** [comment]
The current version looks better to me.  Thanks!
